#!/bin/bash
#SBATCH --qos=regular
#SBATCH --job-name=submit_stage2_Gd
#SBATCH --output=/scratch/elena/9Li/results/log/submit_stage2_Gd_%j.out
#SBATCH --error=/scratch/elena/9Li/results/log/submit_stage2_Gd_%j.err
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=00:05:00

JOBS_DIR="/scratch/elena/9Li/jobs"
RESULTS_DIR="/scratch/elena/9Li/results"
#RUNS=(2407 2408 2409 2432 2434 2438)
RUNS=(2379)

# Recuperar flags pasadas desde la Etapa 1
EXTRA_FLAGS="${EXTRA_ARGS}"

# ------------------------------------------------------------------------------
# Cálculo dinámico del rango de Slurm contando los .pkl creados en la Etapa 1
# ------------------------------------------------------------------------------
TOTAL_CHUNKS=0

if [[ "$EXTRA_FLAGS" == *"--bkg"* ]]; then
    echo ">> STAGE 2 LAUNCHER (Gd): BACKGROUND MODE DETECTED <<"
    # Contar únicamente chunks de BKG
    for RUN in "${RUNS[@]}"; do
        COUNT=$(ls ${RESULTS_DIR}/run${RUN}/processed/Li9_clusters_chunk_*_BKG.pkl 2>/dev/null | wc -l)
        TOTAL_CHUNKS=$((TOTAL_CHUNKS + COUNT))
    done
else
    echo ">> STAGE 2 LAUNCHER (Gd): SIGNAL MODE DETECTED <<"
    # Contar únicamente chunks de SIGNAL (excluyendo BKG)
    for RUN in "${RUNS[@]}"; do
        COUNT=$(ls ${RESULTS_DIR}/run${RUN}/processed/Li9_clusters_chunk_*.pkl 2>/dev/null | grep -v BKG | wc -l)
        TOTAL_CHUNKS=$((TOTAL_CHUNKS + COUNT))
    done
fi

if [ "$TOTAL_CHUNKS" -eq 0 ]; then
    echo "Error: No .pkl files found for Gd Stage 2 in ${RESULTS_DIR}!"
    exit 1
fi

MAX_INDEX=$((TOTAL_CHUNKS - 1))
ARRAY_RANGE="0-${MAX_INDEX}%10"

echo "--> Found ${TOTAL_CHUNKS} total chunks generated by Stage 1 for Gd"
echo "--> Submitting Stage 2 array with range: ${ARRAY_RANGE}"

# ------------------------------------------------------------------------------
# Lanzamiento del Slurm Array de Multilateración para Gd
# ------------------------------------------------------------------------------
JOB_OUT=$(sbatch \
    --array=${ARRAY_RANGE} \
    --export=ALL,EXTRA_ARGS="${EXTRA_FLAGS}" \
    ${JOBS_DIR}/run_multilat_all_Gd.sh)

JOB_ID=$(echo "$JOB_OUT" | awk '{print $4}')

if [ -z "$JOB_ID" ]; then
    echo "Error: Failed to submit Stage 2 Array for Gd!"
    exit 1
fi

echo "Stage 2 (Gd) submitted with Job ID: ${JOB_ID}"

# ------------------------------------------------------------------------------
# Encadenamiento con Stage 4 Launcher (Gd)
# ------------------------------------------------------------------------------
echo "Submitting Stage 4 launcher (waiting for Stage 2 Job ID: ${JOB_ID})..."

sbatch \
    --dependency=afterany:${JOB_ID} \
    --export=ALL,EXTRA_ARGS="${EXTRA_FLAGS}" \
    ${JOBS_DIR}/submit_stage4_Gd.sh