import os
import glob
import argparse
import pandas as pd
import numpy as np

def main():
    parser = argparse.ArgumentParser(description="Merge refined chunks and apply strict Fiducial Volume selection without plotting.")
    parser.add_argument("--run", type=int, required=True, help="Run number to process")
    args = parser.parse_args()

    run_dir = f"/scratch/elena/9Li/results/run{args.run}/processed"
    
    # 1. Gather all refined chunk files generated by the previous step
    search_pattern = os.path.join(run_dir, "Refine_Li9_clusters_chunk*_BKG.pkl")
    refined_files = sorted(glob.glob(search_pattern))
    
    if not refined_files:
        print(f"Error: No refined chunk files found for Run {args.run} in {run_dir}")
        return

    print(f"Found {len(refined_files)} refined chunk files for Run {args.run}. Merging...")
    
    # Concatenate all data chunks into a single DataFrame
    dfs = [pd.read_pickle(f) for f in refined_files]
    df_all_refined = pd.concat(dfs, ignore_index=True)
    print(f"Total refined clusters loaded: {len(df_all_refined)}")

    if df_all_refined.empty:
        print("Merged dataframe is empty. Terminating script.")
        return

    # 2. Define strict Fiducial Volume (FV) limits
    x_lims = [-20.0, 20.0]
    y_lims = [-62.0, -22.0]
    z_lims = [-138.0, 0.0]

    # 3. Filter candidates: Keep ONLY clusters whose REFINED vertices fall inside the FV
    fv_mask = (df_all_refined['v_x_fine'] >= x_lims[0]) & (df_all_refined['v_x_fine'] <= x_lims[1]) & \
              (df_all_refined['v_y_fine'] >= y_lims[0]) & (df_all_refined['v_y_fine'] <= y_lims[1]) & \
              (df_all_refined['v_z_fine'] >= z_lims[0]) & (df_all_refined['v_z_fine'] <= z_lims[1])

    df_final_fv = df_all_refined[fv_mask].copy()
    print(f"Clusters remaining inside strict FV: {len(df_final_fv)} / {len(df_all_refined)}")

    # 4. Save the final strictly filtered dataset
    output_pkl_path = os.path.join(run_dir, f"Final_FV_Li9_clusters_run{args.run}_BKG.pkl")
    df_final_fv.to_pickle(output_pkl_path)
    print(f"Successfully saved final selection structure to: {output_pkl_path}")

if __name__ == "__main__":
    main()